
CREATE TABLE DB_EXAMPLE ( 
  INT_VALUE     INT NOT NULL, 
  STRING_VALUE  VARCHAR(50), 
  DOUBLE_VALUE  FLOAT, 
  EXAMPLE_LONG  INT, 
  EXAMPLE_DATE  DATETIME ) ; 

CREATE TABLE DB_EXAMPLE_BACKUP ( 
  INT_VALUE     INT NOT NULL, 
  STRING_VALUE  VARCHAR(50), 
  DOUBLE_VALUE  FLOAT, 
  EXAMPLE_LONG  INT, 
  EXAMPLE_DATE  DATETIME ) ; 

CREATE TABLE DB_SAMPLE ( 
  SAMPLE_LONG  INT, 
  SAMPLE_INT   INT, 
  SAMPLE_STR   VARCHAR(50), 
  EXTRA_FLOAT  FLOAT ) ; 

CREATE TABLE DB_LONGSTR ( 
  INT_VALUE     INT NOT NULL, 
  STRING_VALUE  VARCHAR(1500), 
  DOUBLE_VALUE  FLOAT, 
  EXAMPLE_LONG  INT, 
  EXAMPLE_DATE  DATETIME ) ;

CREATE TABLE LONG_EXAMPLE (
  STRING_VALUE  VARCHAR(2500)
); 

CREATE TABLE BLOB_EXAMPLE(
BLOB_VALUE BINARY(20)
);
